---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - warmrunners.warmrunners.io
  resources:
  - warmrunnerpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - warmrunners.warmrunners.io
  resources:
  - warmrunnerpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - warmrunners.warmrunners.io
  resources:
  - warmrunnerpolicies/status
  verbs:
  - get
  - patch
  - update
