---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - actions.github.com
  resources:
  - autoscalingrunnersets
  verbs:
  - get
  - update
- apiGroups:
  - autoscaling.warmrunners.io
  resources:
  - warmrunnerpolicies
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.warmrunners.io
  resources:
  - warmrunnerpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.warmrunners.io
  resources:
  - warmrunnerpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - garm-operator.mercedes-benz.com
  resources:
  - pools
  verbs:
  - get
  - update
