//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityConfig) DeepCopyInto(out *ActivityConfig) {
	*out = *in
	if in.BotLoginDenylist != nil {
		in, out := &in.BotLoginDenylist, &out.BotLoginDenylist
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityConfig.
func (in *ActivityConfig) DeepCopy() *ActivityConfig {
	if in == nil {
		return nil
	}
	out := new(ActivityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArcTarget) DeepCopyInto(out *ArcTarget) {
	*out = *in
	out.RunnerSet = in.RunnerSet
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArcTarget.
func (in *ArcTarget) DeepCopy() *ArcTarget {
	if in == nil {
		return nil
	}
	out := new(ArcTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthRef) DeepCopyInto(out *AuthRef) {
	*out = *in
	in.SecretRef.DeepCopyInto(&out.SecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthRef.
func (in *AuthRef) DeepCopy() *AuthRef {
	if in == nil {
		return nil
	}
	out := new(AuthRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FloorRange) DeepCopyInto(out *FloorRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FloorRange.
func (in *FloorRange) DeepCopy() *FloorRange {
	if in == nil {
		return nil
	}
	out := new(FloorRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GarmTarget) DeepCopyInto(out *GarmTarget) {
	*out = *in
	out.Pool = in.Pool
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GarmTarget.
func (in *GarmTarget) DeepCopy() *GarmTarget {
	if in == nil {
		return nil
	}
	out := new(GarmTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubApp) DeepCopyInto(out *GitHubApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubApp.
func (in *GitHubApp) DeepCopy() *GitHubApp {
	if in == nil {
		return nil
	}
	out := new(GitHubApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubAppIngress) DeepCopyInto(out *GitHubAppIngress) {
	*out = *in
	if in.Tunnel != nil {
		in, out := &in.Tunnel, &out.Tunnel
		*out = new(TunnelSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubAppIngress.
func (in *GitHubAppIngress) DeepCopy() *GitHubAppIngress {
	if in == nil {
		return nil
	}
	out := new(GitHubAppIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubAppList) DeepCopyInto(out *GitHubAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitHubApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubAppList.
func (in *GitHubAppList) DeepCopy() *GitHubAppList {
	if in == nil {
		return nil
	}
	out := new(GitHubAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubAppSpec) DeepCopyInto(out *GitHubAppSpec) {
	*out = *in
	out.PrivateKeyRef = in.PrivateKeyRef
	out.WebhookSecretRef = in.WebhookSecretRef
	in.Ingress.DeepCopyInto(&out.Ingress)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubAppSpec.
func (in *GitHubAppSpec) DeepCopy() *GitHubAppSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubAppStatus) DeepCopyInto(out *GitHubAppStatus) {
	*out = *in
	if in.Installations != nil {
		in, out := &in.Installations, &out.Installations
		*out = make([]Installation, len(*in))
		copy(*out, *in)
	}
	if in.LastDelivery != nil {
		in, out := &in.LastDelivery, &out.LastDelivery
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubAppStatus.
func (in *GitHubAppStatus) DeepCopy() *GitHubAppStatus {
	if in == nil {
		return nil
	}
	out := new(GitHubAppStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubConfig) DeepCopyInto(out *GitHubConfig) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Auth.DeepCopyInto(&out.Auth)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubConfig.
func (in *GitHubConfig) DeepCopy() *GitHubConfig {
	if in == nil {
		return nil
	}
	out := new(GitHubConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Installation) DeepCopyInto(out *Installation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Installation.
func (in *Installation) DeepCopy() *Installation {
	if in == nil {
		return nil
	}
	out := new(Installation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictedLabelSet) DeepCopyInto(out *PredictedLabelSet) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictedLabelSet.
func (in *PredictedLabelSet) DeepCopy() *PredictedLabelSet {
	if in == nil {
		return nil
	}
	out := new(PredictedLabelSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictorConfig) DeepCopyInto(out *PredictorConfig) {
	*out = *in
	out.WorkflowRefreshInterval = in.WorkflowRefreshInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictorConfig.
func (in *PredictorConfig) DeepCopy() *PredictorConfig {
	if in == nil {
		return nil
	}
	out := new(PredictorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueRule) DeepCopyInto(out *QueueRule) {
	*out = *in
	out.PollInterval = in.PollInterval
	out.Cooldown = in.Cooldown
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueRule.
func (in *QueueRule) DeepCopy() *QueueRule {
	if in == nil {
		return nil
	}
	out := new(QueueRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RefNS) DeepCopyInto(out *RefNS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RefNS.
func (in *RefNS) DeepCopy() *RefNS {
	if in == nil {
		return nil
	}
	out := new(RefNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleWindow) DeepCopyInto(out *ScheduleWindow) {
	*out = *in
	if in.Days != nil {
		in, out := &in.Days, &out.Days
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleWindow.
func (in *ScheduleWindow) DeepCopy() *ScheduleWindow {
	if in == nil {
		return nil
	}
	out := new(ScheduleWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Target) DeepCopyInto(out *Target) {
	*out = *in
	if in.Arc != nil {
		in, out := &in.Arc, &out.Arc
		*out = new(ArcTarget)
		**out = **in
	}
	if in.Garm != nil {
		in, out := &in.Garm, &out.Garm
		*out = new(GarmTarget)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Target.
func (in *Target) DeepCopy() *Target {
	if in == nil {
		return nil
	}
	out := new(Target)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelSpec) DeepCopyInto(out *TunnelSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelSpec.
func (in *TunnelSpec) DeepCopy() *TunnelSpec {
	if in == nil {
		return nil
	}
	out := new(TunnelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmRunnerPolicy) DeepCopyInto(out *WarmRunnerPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmRunnerPolicy.
func (in *WarmRunnerPolicy) DeepCopy() *WarmRunnerPolicy {
	if in == nil {
		return nil
	}
	out := new(WarmRunnerPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WarmRunnerPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmRunnerPolicyList) DeepCopyInto(out *WarmRunnerPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WarmRunnerPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmRunnerPolicyList.
func (in *WarmRunnerPolicyList) DeepCopy() *WarmRunnerPolicyList {
	if in == nil {
		return nil
	}
	out := new(WarmRunnerPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WarmRunnerPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmRunnerPolicySpec) DeepCopyInto(out *WarmRunnerPolicySpec) {
	*out = *in
	in.GitHub.DeepCopyInto(&out.GitHub)
	in.Target.DeepCopyInto(&out.Target)
	out.Floor = in.Floor
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = make([]ScheduleWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.QueueRule = in.QueueRule
	if in.Predictor != nil {
		in, out := &in.Predictor, &out.Predictor
		*out = new(PredictorConfig)
		**out = **in
	}
	if in.Activity != nil {
		in, out := &in.Activity, &out.Activity
		*out = new(ActivityConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmRunnerPolicySpec.
func (in *WarmRunnerPolicySpec) DeepCopy() *WarmRunnerPolicySpec {
	if in == nil {
		return nil
	}
	out := new(WarmRunnerPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmRunnerPolicyStatus) DeepCopyInto(out *WarmRunnerPolicyStatus) {
	*out = *in
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.LastDecreaseTime != nil {
		in, out := &in.LastDecreaseTime, &out.LastDecreaseTime
		*out = (*in).DeepCopy()
	}
	if in.PredictedLabelSets != nil {
		in, out := &in.PredictedLabelSets, &out.PredictedLabelSets
		*out = make([]PredictedLabelSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ActivityLabelSets != nil {
		in, out := &in.ActivityLabelSets, &out.ActivityLabelSets
		*out = make([]PredictedLabelSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmRunnerPolicyStatus.
func (in *WarmRunnerPolicyStatus) DeepCopy() *WarmRunnerPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(WarmRunnerPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
